### ISSUE TITLE
[Demos] Crowns not showing when the names are too long

### ISSUE THREAD

**Issue by zw627** [zw627/react-redux-typescript-sass-boilerplate#106]
![Annotation 2020-07-16 063338](https://user-images.githubusercontent.com/31707422/87623568-56636900-c72e-11ea-924e-370662826680.png)

**Comment by zw627** [comment]
## Cause

From [`normalize.scss`](https://github.com/csstools/postcss-normalize#postcss-import-usage):

```CSS
svg:not(:root) {
  overflow: hidden;
}
```

Notes:

- The `:not()` CSS pseudo-class represents elements that do not match a list of selectors. Since it prevents specific items from being selected, it is known as the negation pseudo-class.
- The `:root` CSS pseudo-class matches the root element of a tree representing the document. In HTML, `:root` represents the `<html>` element and is identical to the selector html, except that its specificity is higher.

See also:

- https://github.com/necolas/normalize.css/issues/718

## Solution

Add `overflow: initial !important;` to the `.crown`, this is a niche case, thus the use of `!important` is tolerable:

```SCSS
.crown {
  fill: $color-crown-inactive-darkmode;
  height: 16px;
  width: 20.11px;
  margin-right: 10px;
  overflow: initial !important;
  &.has-crown {
    fill: $color-crown-active;
  }

  #{$light-theme} & {
    fill: $color-crown-inactive-lightmode;
    &.has-crown {
      fill: $color-crown-active;
    }
  }
}
```
