### ISSUE TITLE
[Demos] Counter is shrinked when name is too long in IE 

### ISSUE THREAD

**Issue by zw627** [zw627/react-redux-typescript-sass-boilerplate#124]
**Describe the bug**
Counter is shrinked when name is too long in Internet Explorer 11.

**To Reproduce**
Run the demos in Internet Explorer 11.

**Expected behavior**
Counter should be displayed in its full width.

**Screenshots**
![Annotation 2020-07-18 181255](https://user-images.githubusercontent.com/31707422/87855644-5461fb80-c922-11ea-9fc2-4b29b06b34c6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Internet Explorer
 - Version: 11

**Comment by zw627** [comment]
**Cause**
Internet Explorer is quirky when it comes to `flex`. See also https://github.com/zw627/react-redux-typescript-sass-boilerplate/issues/106.

**Solution**
Add `min-width` solves the problem:

```SCSS
.counter {
  background: $color-theme-darkmode-2;
  display: flex;
  width: 185px;
  min-width: 185px; // For Internet Explorer
}
```

```SCSS
@media (max-width: 580px) {
  .counter {
    width: 155px;
    min-width: 155px; // For Internet Explorer
  }
}
```
