### ISSUE TITLE
[CSS] Disable double tap zoom on mobile devices

### ISSUE THREAD

**Issue by zw627** [zw627/react-redux-typescript-sass-boilerplate#138]
## Description

Tap buttons on counter elements rapidly on mobile devices will trigger zoom in.

**Comment by zw627** [comment]
## Solution

Use `touch-action: manipulation` on all elements:

```SCSS
// Disalbe double tap to zoom in on mobile devices
// See https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action#manipulation
* {
  touch-action: manipulation;
}
```

See also:
- [touch-action: manipulation | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action#manipulation)
- [Disable double-tap “zoom” option in browser on touch devices | StackOverflow](https://stackoverflow.com/a/53236027)
